package pt.technic.apps.minesfinder;

import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;

/**
 *
 * @author Gabriel Massadas
 */

public class MinesFinder extends javax.swing.JFrame {

	private RecordTable recordEasy;
	private RecordTable recordMedium;
	private RecordTable recordHard;
	private RecordTable recordChallenge;
	private RecordTable recordItem;
	private static RecordTable record;

	/**
	 * Creates new form MinesFinder
	 */
	public MinesFinder() {
		initComponents();
		recordEasy = new RecordTable();
		recordMedium = new RecordTable();
		recordHard = new RecordTable();
		recordChallenge = new RecordTable();
		recordItem = new RecordTable();

		readGameRecords();

		labelEasyName.setText(recordEasy.getName(0));
		labelEasyPoints.setText(Long.toString(recordEasy.getScore(0) / 1000));
		labelMediumName.setText(recordMedium.getName(0));
		labelMediumPoints.setText(Long.toString(recordMedium.getScore(0) / 1000));
		labelHardName.setText(recordHard.getName(0));
		labelHardPoints.setText(Long.toString(recordHard.getScore(0) / 1000));
		labelChallengeName.setText(recordChallenge.getName(0));
		labelChallengePoints.setText(Long.toString(recordChallenge.getScore(0)));
		labelItemName.setText(recordItem.getName(0));
		labelItemPoints.setText(Long.toString(recordItem.getScore(0) / 1000));

		recordEasy.addRecordTableListener(new RecordTableListener() {
			@Override
			public void recordUpdated(RecordTable record) {
				recordEasyUpdated(record);
			}
		});

		recordMedium.addRecordTableListener(new RecordTableListener() {
			@Override
			public void recordUpdated(RecordTable record) {
				recordMediumUpdated(record);
			}
		});

		recordHard.addRecordTableListener(new RecordTableListener() {
			@Override
			public void recordUpdated(RecordTable record) {
				recordHardUpdated(record);
			}
		});

		recordChallenge.addRecordTableListener(new RecordTableListener() {
			@Override
			public void recordUpdated(RecordTable record) {
				recordChallengeUpdated(record);
			}
		});

	}

	private void recordEasyUpdated(RecordTable record) {
		labelEasyName.setText(record.getName(0));
		labelEasyPoints.setText(Long.toString(record.getScore(0) / 1000));
		saveGameRecords();
	}

	private void recordMediumUpdated(RecordTable record) {
		labelMediumName.setText(record.getName(0));
		labelMediumPoints.setText(Long.toString(record.getScore(0) / 1000));
		saveGameRecords();
	}

	private void recordHardUpdated(RecordTable record) {
		labelHardName.setText(record.getName(0));
		labelHardPoints.setText(Long.toString(record.getScore(0) / 1000));
		saveGameRecords();
	}

	private void recordChallengeUpdated(RecordTable record) {
		labelChallengeName.setText(record.getChName(0));
		labelChallengePoints.setText(Long.toString(record.getChScore(0)));
		saveGameRecords();
	}

	private void saveGameRecords() {
		ObjectOutputStream oos = null;
		try {
			File f = new File(System.getProperty("user.home") + File.separator + ".minesfinder.records");
			oos = new ObjectOutputStream(new FileOutputStream(f));
			oos.writeObject(recordEasy);
			oos.writeObject(recordMedium);
			oos.writeObject(recordHard);
			oos.writeObject(recordChallenge);
			oos.writeObject(recordItem);
			oos.close();
		} catch (IOException ex) {
			Logger.getLogger(MinesFinder.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void readGameRecords() {
		ObjectInputStream ois = null;
		File f = new File(System.getProperty("user.home") + File.separator + ".minesfinder.records");
		if (f.canRead()) {
			try {
				ois = new ObjectInputStream(new FileInputStream(f));
				recordEasy = (RecordTable) ois.readObject();
				recordMedium = (RecordTable) ois.readObject();
				recordHard = (RecordTable) ois.readObject();
				recordChallenge = (RecordTable) ois.readObject();
				ois.close();
			} catch (IOException | ClassNotFoundException ex) {
				Logger.getLogger(MinesFinder.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {
		panelTitle = new javax.swing.JLabel();
		panelRecords = new javax.swing.JPanel();
		panelNormal = new javax.swing.JPanel();
		Records = new javax.swing.JLabel();
		labelEasy = new javax.swing.JLabel();
		labelEasyName = new javax.swing.JLabel();
		labelEasyPoints = new javax.swing.JLabel();
		labelMedium = new javax.swing.JLabel();
		labelMediumName = new javax.swing.JLabel();
		labelMediumPoints = new javax.swing.JLabel();
		labelHard = new javax.swing.JLabel();
		labelHardName = new javax.swing.JLabel();
		labelHardPoints = new javax.swing.JLabel();
		labelChallenge = new javax.swing.JLabel();
		labelChallengeName = new javax.swing.JLabel();
		labelChallengePoints = new javax.swing.JLabel();
		labelItem = new javax.swing.JLabel();
		labelItemName = new javax.swing.JLabel();
		labelItemPoints = new javax.swing.JLabel();
		labelRecordMenu = new javax.swing.JLabel();
		labelNormal = new javax.swing.JLabel();
		panelBtns = new javax.swing.JPanel();
		btnEasy = new javax.swing.JButton();
		btnMedium = new javax.swing.JButton();
		btnHard = new javax.swing.JButton();
		btnChallenge = new javax.swing.JButton();
		btnItem = new javax.swing.JButton();
		btnRecordMenu = new javax.swing.JButton();
		// btnExit = new javax.swing.JButton();
		btnNormal = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MinesFinder");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setPreferredSize(new java.awt.Dimension(600, 450));
		setResizable(false);

		panelTitle.setBackground(new java.awt.Color(136, 135, 217));
		panelTitle.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		panelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		panelTitle.setText("Minesfinder");
		panelTitle.setOpaque(true);
		getContentPane().add(panelTitle, java.awt.BorderLayout.PAGE_START);

		panelRecords.setBackground(new java.awt.Color(118, 206, 108));

		Records.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
		Records.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Records.setText("Records");

		labelEasy.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
		labelEasy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelEasy.setText("Easy");

		labelEasyName.setText("Player");

		labelEasyPoints.setText("9999");

		labelMedium.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
		labelMedium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelMedium.setText("Medium");

		labelMediumName.setText("Player");

		labelMediumPoints.setText("9999");

		labelHard.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
		labelHard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelHard.setText("Hard");

		labelHardName.setText("Player");

		labelHardPoints.setText("9999");

		labelChallenge.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
		labelChallenge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelChallenge.setText("Challenge");

		labelChallengeName.setText("Player");

		labelChallengePoints.setText("9999");

		labelItem.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
		labelItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelItem.setText("Item");

		labelItemName.setText("Player");

		labelItemPoints.setText("9999");

		javax.swing.GroupLayout panelRecordsLayout = new javax.swing.GroupLayout(panelRecords);
		panelRecords.setLayout(panelRecordsLayout);
		panelRecordsLayout.setHorizontalGroup(panelRecordsLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(labelEasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(Records, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(panelRecordsLayout.createSequentialGroup().addContainerGap()
						.addGroup(panelRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panelRecordsLayout.createSequentialGroup().addComponent(labelEasyName)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(labelEasyPoints))
								.addComponent(labelMedium, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(panelRecordsLayout.createSequentialGroup().addComponent(labelMediumName)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(labelMediumPoints))
								.addComponent(labelHard, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(panelRecordsLayout.createSequentialGroup().addComponent(labelHardName)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(labelHardPoints)))
						.addContainerGap()));
		panelRecordsLayout.setVerticalGroup(panelRecordsLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelRecordsLayout.createSequentialGroup().addComponent(Records).addGap(18, 18, 18)
						.addComponent(labelEasy).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(labelEasyPoints).addComponent(labelEasyName))
						.addGap(18, 18, 18).addComponent(labelMedium)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(labelMediumPoints).addComponent(labelMediumName))
						.addGap(18, 18, 18).addComponent(labelHard)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(labelHardPoints).addComponent(labelHardName))
						.addGap(0, 169, Short.MAX_VALUE)));

		getContentPane().add(panelRecords, java.awt.BorderLayout.LINE_START);

		panelNormal.setLayout(new java.awt.GridLayout(3, 0));
		panelBtns.setLayout(new java.awt.GridLayout(2, 0));

		btnNormal.setFont(new Font("Gothic", Font.BOLD, 20));
		btnNormal.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/pt/technic/apps/minesfinder/resources/easy.png"))); // NOI18N
		btnNormal.setText("Normal");

		btnNormal.setHorizontalTextPosition(JButton.CENTER);
		btnNormal.setVerticalTextPosition(JButton.CENTER);
		btnNormal.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNormalActionPerformed(evt);
			}
		});
		panelBtns.add(btnNormal);

		btnEasy.setText("Easy");
		btnEasy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEasyActionPerformed(evt);
			}
		});
		panelNormal.add(btnEasy);

		btnMedium.setText("Medium");
		btnMedium.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnMediumActionPerformed(evt);
			}
		});
		panelNormal.add(btnMedium);

		btnHard.setText("Hard");
		btnHard.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHardActionPerformed(evt);
			}
		});
		panelNormal.add(btnHard);

		btnChallenge.setIcon(new javax.swing.ImageIcon(
				getClass().getResource("/pt/technic/apps/minesfinder/resources/challenge.png"))); // NOI18N 이미지 바꾸기
		btnChallenge.setText("ChallengeMode");
		btnChallenge.setFont(new Font("Gothic", Font.BOLD, 20));
		btnChallenge.setHorizontalTextPosition(JButton.CENTER);
		btnChallenge.setVerticalTextPosition(JButton.CENTER);
		btnChallenge.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnChallengeActionPerformed(evt);
			}
		});
		panelBtns.add(btnChallenge);

		btnItem.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/pt/technic/apps/minesfinder/resources/item.png"))); // NOI18N
																														// 이미지
																														// 바꾸기
		btnItem.setText("ItemMode");
		btnItem.setFont(new Font("Gothic", Font.BOLD, 20));
		btnItem.setHorizontalTextPosition(JButton.CENTER);
		btnItem.setVerticalTextPosition(JButton.CENTER);
		btnItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnItemActionPerformed(evt);
			}
		});
		panelBtns.add(btnItem);

		/*
		 * btnExit.setText("Exit"); btnExit.addActionListener(new
		 * java.awt.event.ActionListener() { public void
		 * actionPerformed(java.awt.event.ActionEvent evt) {
		 * btnExitActionPerformed(evt); } }); panelBtns.add(btnExit);
		 */

		btnRecordMenu.setText("Record");
		btnRecordMenu.setFont(new Font("Gothic", Font.BOLD, 20));
		btnRecordMenu.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/pt/technic/apps/minesfinder/resources/record.png")));
		btnRecordMenu.setHorizontalTextPosition(JButton.CENTER);
		btnRecordMenu.setVerticalTextPosition(JButton.CENTER);
		btnRecordMenu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRecordMenuActionPerformed(evt);
			}
		});
		panelBtns.add(btnRecordMenu);

		getContentPane().add(panelBtns, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public static RecordTable getRecord() {
		return record;
	}

	private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHardActionPerformed
		Normal normal = new Normal();
		normal.Normal();
	}// GEN-LAST:event_btnHardActionPerformed

	private void btnEasyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEasyActionPerformed
		GameWindowNormal gameWindow = new GameWindowNormal(new Minefield(9, 9, 10), recordEasy);		
		record = recordEasy;
		gameWindow.setVisible(true);
	}// GEN-LAST:event_btnEasyActionPerformed

	private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMediumActionPerformed
		GameWindowNormal gameWindow = new GameWindowNormal(new Minefield(16, 16, 40), recordMedium);		
		record = recordMedium;
		gameWindow.setVisible(true);
	}// GEN-LAST:event_btnMediumActionPerformed

	private void btnHardActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHardActionPerformed
		GameWindowNormal gameWindow = new GameWindowNormal(new Minefield(16, 30, 90), recordHard);		
		record = recordHard;
		gameWindow.setVisible(true);
	}// GEN-LAST:event_btnHardActionPerformed

	private void btnChallengeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHardActionPerformed
		GameWindowCh gameWindow = new GameWindowCh(new Minefield(4, 4, 3), recordChallenge);		
		record = gameWindow.record();
		gameWindow.setVisible(true);
	}// GEN-LAST:event_btnHardActionPerformed

	private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHardActionPerformed
		GameWindowItem gameWindow = new GameWindowItem(new Minefield(9, 9, 10), recordItem);		
		record = recordItem;
		gameWindow.setVisible(true);
	}// GEN-LAST:event_btnHardActionPerformed

	private void btnRecordMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHardActionPerformed
		RecordMenu recordmenu = new RecordMenu(recordEasy, recordMedium, recordHard, recordChallenge);
	}// GEN-LAST:event_btnHardActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MinesFinder().setVisible(true);
			}
		});

		Sound mainmusic = new Sound();
		while (true) {
			try {
				mainmusic.mainmusicPlay();
				Thread.sleep(68000); // 68초에 한번씩 재생하도록 설정
			} catch (Exception e) {

			}
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel Records;
	public static javax.swing.JButton btnEasy;
	// public javax.swing.JButton btnExit;
	public static javax.swing.JButton btnHard;
	public static javax.swing.JButton btnMedium;
	public javax.swing.JButton btnChallenge;
	public javax.swing.JButton btnItem;
	public javax.swing.JButton btnRecordMenu;
	public javax.swing.JButton btnNormal;
	private javax.swing.JLabel labelEasy;
	private javax.swing.JLabel labelEasyName;
	private javax.swing.JLabel labelEasyPoints;
	private javax.swing.JLabel labelHard;
	private javax.swing.JLabel labelHardName;
	private javax.swing.JLabel labelHardPoints;
	private javax.swing.JLabel labelMedium;
	private javax.swing.JLabel labelMediumName;
	private javax.swing.JLabel labelMediumPoints;
	private javax.swing.JLabel labelChallenge;
	private javax.swing.JLabel labelChallengeName;
	private javax.swing.JLabel labelChallengePoints;
	private javax.swing.JLabel labelItem;
	private javax.swing.JLabel labelItemName;
	private javax.swing.JLabel labelItemPoints;
	private javax.swing.JLabel labelRecordMenu;
	private javax.swing.JLabel labelNormal;
	private javax.swing.JPanel panelBtns;
	private javax.swing.JPanel panelRecords;
	public static javax.swing.JPanel panelNormal;
	private javax.swing.JLabel panelTitle;
	// End of variables declaration//GEN-END:variables
}
